# Generated by Django 4.1.13 on 2023-12-06 18:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, null=True)),
                ('seats', models.IntegerField(null=True)),
                ('row', models.IntegerField(null=True)),
                ('column', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rows', models.IntegerField(null=True)),
                ('Columns', models.IntegerField(null=True)),
                ('Tables', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantTitle', models.CharField(max_length=50)),
                ('EmployeeeIDS', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('Status', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('RestaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastro.person')),
                ('TableGridID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastro.tablegrid')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableId', models.IntegerField(null=True)),
                ('DateTimeFrom', models.DateTimeField()),
                ('DateTimeTo', models.DateTimeField()),
                ('PersonId', models.IntegerField(null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastro.person')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.TextField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastro.person')),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastro.restaurant')),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastro.table')),
            ],
        ),
    ]
