# Generated by Django 4.1.13 on 2023-12-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastro', '0002_person_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='RestaurantID',
            new_name='OwnerID',
        ),
    ]
